# Generated by Django 4.2.16 on 2024-12-04 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FromFactoryToStorageDistance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('storage_name', models.CharField(max_length=100)),
                ('storage_distance', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Storage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('plastic_current', models.IntegerField(default=0)),
                ('plastic_max', models.IntegerField(default=0)),
                ('glass_current', models.IntegerField(default=0)),
                ('glass_max', models.IntegerField(default=0)),
                ('bio_waste_current', models.IntegerField(default=0)),
                ('bio_waste_max', models.IntegerField(default=0)),
            ],
        ),
    ]
