# Generated by Django 4.2.16 on 2024-12-04 15:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('waste_management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Factory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RenameField(
            model_name='fromfactorytostoragedistance',
            old_name='storage_distance',
            new_name='distance',
        ),
        migrations.RemoveField(
            model_name='fromfactorytostoragedistance',
            name='name',
        ),
        migrations.RemoveField(
            model_name='fromfactorytostoragedistance',
            name='storage_name',
        ),
        migrations.AddField(
            model_name='fromfactorytostoragedistance',
            name='storage',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='factory_distances', to='waste_management.storage'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fromfactorytostoragedistance',
            name='factory',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='storage_distances', to='waste_management.factory'),
            preserve_default=False,
        ),
    ]
