# Generated by Django 4.2.16 on 2024-12-07 09:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('waste_management', '0002_factory_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fromfactorytostoragedistance',
            name='factory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='factory_distances', to='waste_management.factory'),
        ),
        migrations.AlterField(
            model_name='fromfactorytostoragedistance',
            name='storage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='storage_distances', to='waste_management.storage'),
        ),
    ]
